// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJ1AyVxupO4BT87D4lJ7qcl0SZmcY6fMA',
    appId: '1:14553747706:web:ac51f9b4cc676b35c5b943',
    messagingSenderId: '14553747706',
    projectId: 'wallet-app-4fcc2',
    authDomain: 'wallet-app-4fcc2.firebaseapp.com',
    storageBucket: 'wallet-app-4fcc2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdMEMHZuSstcGsu0aOhOSrmV_MKodZoYk',
    appId: '1:14553747706:android:4bbcc9a50ce78bdac5b943',
    messagingSenderId: '14553747706',
    projectId: 'wallet-app-4fcc2',
    storageBucket: 'wallet-app-4fcc2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDr5Asy5GzdGNv5mwtYcYH-EIa1jn_KtpA',
    appId: '1:14553747706:ios:1730b73763f4fc2ec5b943',
    messagingSenderId: '14553747706',
    projectId: 'wallet-app-4fcc2',
    storageBucket: 'wallet-app-4fcc2.appspot.com',
    androidClientId: '14553747706-k3kg9mmq9bvjnltkg3lug7s7g6nhs0ti.apps.googleusercontent.com',
    iosClientId: '14553747706-0euqmp7kun7dfskob0dc6r0j7eguqgc0.apps.googleusercontent.com',
    iosBundleId: 'com.example.walletApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDr5Asy5GzdGNv5mwtYcYH-EIa1jn_KtpA',
    appId: '1:14553747706:ios:1730b73763f4fc2ec5b943',
    messagingSenderId: '14553747706',
    projectId: 'wallet-app-4fcc2',
    storageBucket: 'wallet-app-4fcc2.appspot.com',
    androidClientId: '14553747706-k3kg9mmq9bvjnltkg3lug7s7g6nhs0ti.apps.googleusercontent.com',
    iosClientId: '14553747706-0euqmp7kun7dfskob0dc6r0j7eguqgc0.apps.googleusercontent.com',
    iosBundleId: 'com.example.walletApp',
  );
}
